# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- refs/tags/v*

pool:
  vmImage: ubuntu-22.04

steps:
- task: NodeTool@0
  displayName: 'Install Node 16.x'
  inputs:
    versionSpec: 16.x

- script: |
   npm install -g @angular/cli@14.x
   npm install
   ng build --configuration production
  displayName: 'NPM and Angular 14 install, and build Frontend software'


